### ISSUE TITLE
Column type DECIMAL(N,1) maps to Decimal('NaN')

### ISSUE THREAD

**Issue by gygabyte017** [Teradata/sqlalchemy-teradata#24]
Suppose we have this table:
`CREATE TABLE TEST (ID INTEGER, D DECIMAL(2,1));

INSERT INTO TEST(-1, 1.5); `

If I execute:
```
from sqlalchemy import create_engine
td_engine = create_engine('teradata://'+ user +':' + pasw + '@'+ host + ':22/')

print(td_engine.execute("SELECT * FROM TEST").fetchall())
```
I get:
```
[(Decimal('-1'), Decimal('NaN')]
```
So I get Decimal('NaN') instead of Decimal('1.5').

This happens every time I have a Teradata column type of DECIMAL(N,M) with M > 0.

What is wrong?

**Comment by sandan** [comment]
@gygabyte017 I have tried the example and it works for me:
`In [22]: td_engine.execute('sel * from sqla_db.test').fetchall()`
`Out[22]: [(Decimal('-1'), Decimal('1.5'))]`

**Comment by gygabyte017** [comment]
Sorry I forgot to reply, I found out that this issue is related to regional settings (the period separated numbers get converted to comma separated numbers and perhaps python trying to parse them gets NaN).

Maybe you don't get the issue since you have American regional settings (I have Italian ones).

So a solution is to put

`USEREGIONALSETTINGS="No"`

in the odbc connection string.

**Comment by sandan** [comment]
@gygabyte017 thanks!

**Comment by mencwelp** [comment]
Have same issue here  im not usuing ODBC just regular  connection 
url = ("teradata://"+user+":"+pasw+"@"+host+"/?authentication=LDAP?driver=Teradata")
I have try to add your parameter 
url = ("teradata://"+user+":"+pasw+"@"+host+"/?authentication=LDAP?USEREGIONALSETTINGS=No?driver=Teradata")
but its not working for me :( 
any other idea ?
