### ISSUE TITLE
engine `table_names` always returns empty list

### ISSUE THREAD

**Issue by julioasotodv** [Teradata/sqlalchemy-teradata#25]
I guess this is because of a missing implementation, but the following code does not return any results:

```python
from sqlalchemy import create_engine
teradata_engine = create_engine("teradata://myuser:mypass@teradata-host:22/mydb")

table_names = teradata_engine.table_names()  # Always returns an empty list
```

Given pandas' `read_sql_table()` relies on this exact same code (and on `table_names` being the list of table names), there is no way to read tables from pandas.

**Comment by mrbungie** [comment]
What does this query output using that same user?

`SELECT * FROM dbc.TablesVX WHERE DatabaseName = 'mydb' AND tablekind in ('T','O');`

**Comment by sandan** [comment]
@julioasotodv 
It work for me:
`In [25]: len(td_engine.table_names())`
`Out[25]: 200`

Perhaps the database you are on has no tables?
