### ISSUE TITLE
Error while connecting to Teradata using Python

### ISSUE THREAD

**Issue by mraduldhakad1** [Teradata/sqlalchemy-teradata#26]
Hi All ,

I am getting below Error while connecting Teradata using Python:
File "C:\Python27\Lib\site-packages\teradata\udaexec.py", line 183, in connect
**args))
File "C:\Python27\Lib\site-packages\teradata\tdodbc.py", line 427, in __init__
connectParams["DRIVER"] = determineDriver(dbType, driver)
File "C:\Python27\Lib\site-packages\teradata\tdodbc.py", line 391, in determineDriver
"Available drivers: {}".format(dbType, ",".join(drivers)))
InterfaceError: ('DRIVER_NOT_FOUND', "No driver found for 'Teradata'
I am using below code to connect :

import teradata
udaExec = teradata.UdaExec (appName="HelloWorld", version="1.0",
logConsole=False)
session = udaExec.connect(method="odbc", system="xxx",
username="xxx", password="xxx");

Could anyone please let me know how to resolve this  Error

**Comment by tserafim** [comment]
Well, according to the stack trace, the driver was not found. 

This sqlalchemy dialects uses ODBC connection(through Teradata python module) so you need to install (and configure?) the odbc driver for windows: http://downloads.teradata.com/download/connectivity/odbc-driver/windows

**Comment by mraduldhakad1** [comment]
This is already install on machine.

**Comment by tserafim** [comment]
Change your code and make `logConsole=True` and try again.
In the log, look for `teradata.tdodbc - INFO - Available drivers:`

Do you see Teradata in that list? If not, than I would guess the driver isn´t properly installed.

By the way, the things we are discussing are not related to the sqlalchemy dialtect, but are related to the Teradata python package: https://github.com/Teradata/PyTd
Maybe they can provide you better answers.

**Comment by mrbungie** [comment]
Did you check if your ODBC driver is the same arquitecture as your Python interpreter? They should be the same (64 bits ODBC and Python).

**Comment by sandan** [comment]
@mraduldhakad1 Any updates?
