### ISSUE TITLE
Schema meaning in dialect implementation

### ISSUE THREAD

**Issue by mrbungie** [Teradata/sqlalchemy-teradata#3]
I have some doubts about what a schema represents. I know that every user is a Database in Teradata,  and by that definition using the username as a default schema/database (creatorname in the implementation though) is quite sensible.

However, not every Database is a user, and by that definition it's quite possible that I might wanna query to an arbitrary schema/database. As far as I can tell, this implementation won't take that into account.

i.e. Assume there is a table [SchemaDatabase1].[Table1], I'm user1 and while I didn't create the table I'm allowed to SELECT it. If my code eventually reaches TeradataDialect.has_table(conn, "Table1", schema="SchemaDatabase1") it will return false even if it exists. Check both the statement at https://github.com/Teradata/sqlalchemy-teradata/blob/master/sqlalchemy_teradata/dialect.py#L81 and DBC.TablesVX definition if you want to verify it.

Is this behavior by design? It might be my opinion, but it limits sqlalchemy capabilities a lot.

**Comment by sandan** [comment]
According to the documentation it looks like CreatorName references the same column as DataBaseName. I have created the scenario you mentioned in your post and it returns True.

Maybe CreatorName is misleading?

**Comment by mrbungie** [comment]
I think it is. At least on our case CreatorName points towards the user that created the table and not the schema itself. 

Obviously there is the possibility where a user creates a table on his own database, and that would mean CreatorName == DatabaseName, but that's only one case.

I think using DatabaseName would be a better aproach here, since it would cover all situations.

**Comment by mrbungie** [comment]
I was looking for more evidence. It looks like even when they reference the same column, they're constrained in different ways. 

dbase.DatabaseName (DatabaseName) is constrained on tvm.DatabaseId = dbase.DatabaseId, while DB1.DatabaseName (CreatorName) is constrained on DBC.tvm.CreateUID = DB1.DatabaseID.  That should mean that dbase.DatabaseName corresponds to the tvm (for Table View Macro) DatabaseName and DB1.DatabaseName corresponds to the user DatabaseName.

http://www.elsasoft.org/samples/teradata/Teradata.127.0.0.1.DBC/view_TablesVX.htm

I will make a PR, so you can check it.
