### ISSUE TITLE
Can't load teradata dialect

### ISSUE THREAD

**Issue by shredmore** [Teradata/sqlalchemy-teradata#33]
Hi,

I'm hoping this is simple user error or installation issue but some reason I'm getting the following error:

`Can't load plugin: sqlalchemy.dialects:teradata`

This is my first attempt to connect to teradata and I'm using the example code:

`user = 'my_user' ` 
`pasw= 'my_pw'  `
`host = 'my_host'  `

`td_engine = create_engine('teradata://'+ user +':' + pasw + '@'+ host + '/' + '?authentication=LDAP')`

I looked in the sqlalchemy dialects folder and teradata is not one of the dialects present after `pip install sqlalchemy-teradata`.

Any help would be appreciated. Thanks!

**Comment by sandan** [comment]
@shredmore Do you see the problem when you only specify the `authentication` in the connection url? Did you have another version of `sqlalchemy` installed?

**Comment by binilg** [comment]
I am also facing the same issue? Do we have a resolution for this?
