### ISSUE TITLE
Can't populate Teradata timestamps via Flask-SQLAlchemy calls

### ISSUE THREAD

**Issue by SV100007** [Teradata/sqlalchemy-teradata#34]
This issue is a general question around Flask-SQLAlchemy over Teradata. It may not relate to the sqlalchemy-teradata project.

I'm trying to insert into a Teradata table via a Flask-SQLAlchemy REST API. Using code like the below. Works fine with character and integer type columns, but I can't get it to handle Timestamps. 

It's generating an Insert Values statement, and it can't come up with something like TIMESTAMP '1900-01-01 00:00:00.000000'.

Any hints or assistance would be greatly appreciated.

''' Stream Id '''
try:
    print_msg ("Assembling new Stream Id record.")
    ucf_stream_id = UCFStreamId ()
    ucf_stream_id.stream_key = stream_key_int
    ucf_stream_id.next_business_date = next_business_date_dt
    ucf_stream_id.prev_business_date = datetime.strptime("1900-01-01", '%Y-%m-%d').date()
    ucf_stream_id.processing_flag = 1

except:
    print_msg ("Error: Failed to assemble new Stream Id record.")
    abort (status.HTTP_500_INTERNAL_SERVER_ERROR)

try:
    print_msg ("Inserting new Stream Id record.")
    db.session.add (ucf_stream_id)
    db.session.commit ()
    print_msg ("Change committed to database.")

**Comment by sandan** [comment]
@SV100007 What is the error that you are getting exactly? I'm thinking your problem is related to this line:

ucf_stream_id.prev_business_date = datetime.strptime("1900-01-01", '%Y-%m-%d').date()`

Note that the right hand side evaluates to a date (which doesn't include a time), so that is likely why you are receiving your error. You are trying to insert a date into an underlying table with a Timestamp column. However, the name of the attribute (`prev_business_date`) seems to imply the value should be a date.

If this is the case, try something like this as the value instead:
`from datetime import datetime`
`datetime.utcnow()`

**Comment by SV100007** [comment]
Hi Mark

Sorry I wasn’t clear. The line you indicate works fine, assigning a value to a date column. My problem lies with TIMESTAMP columns.

If I try to set a timestamp column using something like

ucf_stream_id.prev_business_ts = datetime.strptime("1900-01-01", '%Y-%m-%d')

I get the Teradata error “invalid timestamp”.

Below is some test code which simulates the actual app. The UCFTest model has a column of type TIMESTAMP, but it wont accept nullable, info, etc and is not included in the generated SQL. It fails with the error

[Teradata][ODBC Teradata Driver][Teradata Database] Column 'test_ts' is NOT NULL.  Give the column a value. ") [SQL: 'INSERT INTO "GCFR_test" (ctl_id) VALUES (?)'] [parameters: (1,)]

I don’t understand how the model columns are validated and converted into SQL.I don’t know whether to use the Teradata TIMESTAMP data type, or try a SQLAlchemy type like DateTime.

The DDL for the test table is at the bottom.

Thanks again for your help.

from datetime import datetime
# from ucf.webapp import create_flask_app
from ucf.webapp.utils.base_model import ModelBase
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_marshmallow import Marshmallow
from flask_migrate import Migrate

from ucf.webapp.utils.flask_sqlalchemy_teradata import SQLAlchemyTeradata
from ucf.webapp.app_config import flask_app_config

__author__ = "Frank Wang, frank.wang@teradata.com"
# audit column list in model

db = SQLAlchemyTeradata()
ma = Marshmallow()
login_manager = LoginManager()

def create_flask_app(config_name):
    """
    create flask app instance
    :param config_name: ['PROD', 'DEV', 'TEST']
    :return: flask app instance
    """
    if not config_name:
        config_name = 'PROD'
    if not flask_app_config[config_name]:
        config_name = 'PROD'


    app = Flask(__name__)
    app.config.from_object(flask_app_config[config_name])
    Bootstrap(app)
    db.init_app(app)
    ma.init_app(app)

    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"
    migrate = Migrate(app, db)

    @app.errorhandler(403)
    def forbidden(error):
        return render_template('errors/403.html', title='Forbidden'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html', title='Page Not Found'), 404

    @app.errorhandler(500)
    def internal_server_error(error):
        return render_template('errors/500.html', title='Server Error'), 500

    return app

class UCFTest(ModelBase):
    __tablename__ = 'GCFR_test'

    ctl_id = db.Column (db.Integer, primary_key=True, nullable=False, info={'label': 'ctl_id'})
    # test_ts = db.column(db.DateTime, nullable=False, info={'label': 'test_ts'})
    test_ts = db.column(db.TIMESTAMP)

    def __repr__(self):
        return "<UCFTest(ctl_id=%d)>" % self.ctl_id

def testx():
    app_config_alias = 'DEV'
    app = create_flask_app(app_config_alias)

    class ucftest_schema (ma.ModelSchema):
        class Meta:
            model = UCFTest

    with app.app_context():
        ucf_test = UCFTest()
        ucf_test.ctl_id = 1
        ucf_test.test_ts = datetime.strptime("1900-01-01", '%Y-%m-%d')

        # try:
        db.session.add (ucf_test)
        db.session.commit ()

if __name__ == '__main__':
    testx()



CREATE SET TABLE GDEV1T_GCFR.GCFR_TEST ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ctl_Id SMALLINT NOT NULL,
      test_ts TIMESTAMP(6) NOT NULL,
      Update_Date DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      Update_User VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL DEFAULT USER ,
      Update_Ts TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6))
UNIQUE PRIMARY INDEX ( Ctl_Id );

**Comment by sandan** [comment]
The column test_ts has type TIMESTAMP(6). The `6` means precision of 6, that is the Time part of the Timestamp has 6 digits after the seconds (microsecond granularity).

The Timestamp value given by `datetime.strptime("1900-01-01", '%Y-%m-%d')` probably doesn't have the precision part right. The value you insert looks like `1900-01-01 00:00:00`. It should look like `1900-01-01 00:00:00.000000`. 

So try datetime(1900, 1, 1, 0, 0, 0, 1). It looks like datetime(1900, 1, 1, 0, 0, 0, 0) doesn't include the microsecond part when the microsecond value is 0.

**Comment by SV100007** [comment]
Hi Mark

I’m OK on the Teradata side (25+ years)  – it’s SQLAlchemy I don’t understand well. I find it difficult to locate the place in the code where errors are originating.

I added your suggested assignment (below).

If I use a data type of TIMESTAMP in the model declaration, it won’t accent “nullable”, “info”, etc, and the column is just ignored in the generated INSERT statement, causing a “Give the column a value” error.

If I use the DateTime data type, it doesn’t’ like “nullable” either (see error below). “nullable” and “info” work fine for Integer and String data types. Why is this?

I think I could crack this if I could find the place that validates the column declaration in the model and see how its converted into SQL in db.session.add.

Traceback (most recent call last):
  File "C:/github/caesar/Reference/UCF/pyUCF/z.py", line 57, in <module>
   class UCFTest(ModelBase):
  File "C:/github/caesar/Reference/UCF/pyUCF/z.py", line 61, in UCFTest
    test_ts = db.column(db.DateTime, nullable=False, info={'label': 'test_ts'})
TypeError: column() got an unexpected keyword argument 'nullable'

class UCFTest(ModelBase):
    __tablename__ = 'GCFR_test'

    ctl_id = db.Column (db.Integer, primary_key=True, nullable=False, info={'label': 'ctl_id'})
    test_ts = db.column(db.DateTime, nullable=False, info={'label': 'test_ts'})
    #test_ts = db.column(db.TIMESTAMP)

    def __repr__(self):
        return "<UCFTest(ctl_id=%d)>" % self.ctl_id

def testx():
    app_config_alias = 'DEV'
    app = create_flask_app(app_config_alias)

    class ucftest_schema (ma.ModelSchema):
        class Meta:
            model = UCFTest

    with app.app_context():
        ucf_test = UCFTest()
        ucf_test.ctl_id = 1
        ucf_test.test_ts = datetime(1900, 1, 1, 0, 0, 0, 1)
        #ucf_test.test_ts = datetime.strptime("1900-01-01", '%Y-%m-%d')

        # try:
        db.session.add (ucf_test)
        db.session.commit ()

**Comment by FrankWangAU** [comment]
Hi @SV100007 ,

Can you paste the full content of this file: C:/github/caesar/Reference/UCF/pyUCF/z.py

**Comment by SV100007** [comment]
Im available on Slack.

All assistance valued and appreciated.

from datetime import datetime
# from ucf.webapp import create_flask_app
from ucf.webapp.utils.base_model import ModelBase
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_marshmallow import Marshmallow
from flask_migrate import Migrate

from ucf.webapp.utils.flask_sqlalchemy_teradata import SQLAlchemyTeradata
from ucf.webapp.app_config import flask_app_config

__author__ = "Frank Wang, frank.wang@teradata.com"
# audit column list in model

db = SQLAlchemyTeradata()
ma = Marshmallow()
login_manager = LoginManager()

def create_flask_app(config_name):
    """
    create flask app instance
    :param config_name: ['PROD', 'DEV', 'TEST']
    :return: flask app instance
    """
    if not config_name:
        config_name = 'PROD'
    if not flask_app_config[config_name]:
        config_name = 'PROD'


    app = Flask(__name__)
    app.config.from_object(flask_app_config[config_name])
    Bootstrap(app)
    db.init_app(app)
    ma.init_app(app)

    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"
    migrate = Migrate(app, db)

    @app.errorhandler(403)
    def forbidden(error):
        return render_template('errors/403.html', title='Forbidden'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html', title='Page Not Found'), 404

    @app.errorhandler(500)
    def internal_server_error(error):
        return render_template('errors/500.html', title='Server Error'), 500

    return app

class UCFTest(ModelBase):
    __tablename__ = 'GCFR_test'

    ctl_id = db.Column (db.Integer, primary_key=True, nullable=False, info={'label': 'ctl_id'})
    test_ts = db.column(db.DateTime, nullable=False, info={'label': 'test_ts'})
    #test_ts = db.column(db.TIMESTAMP)

    def __repr__(self):
        return "<UCFTest(ctl_id=%d)>" % self.ctl_id

def testx():
    app_config_alias = 'DEV'
    app = create_flask_app(app_config_alias)

    class ucftest_schema (ma.ModelSchema):
        class Meta:
            model = UCFTest

    with app.app_context():
        ucf_test = UCFTest()
        ucf_test.ctl_id = 1
        ucf_test.test_ts = datetime(1900, 1, 1, 0, 0, 0, 1)
        #ucf_test.test_ts = datetime.strptime("1900-01-01", '%Y-%m-%d')

        # try:
        db.session.add (ucf_test)
        db.session.commit ()

if __name__ == '__main__':
    testx()

**Comment by FrankWangAU** [comment]
Hi @SV100007 
Try to change "db.column" to "db.**C**olumn" in following line.
  test_ts = db.column(db.DateTime, nullable=False, info={'label': 'test_ts'})
Python language is case sensitive .

BTW: Im NOT available on Slack. J

**Comment by SV100007** [comment]
I have to say that that’s more than a little embarrassing.

Working now for both DateTime and TIMESTAMP data types.

Didn’t learn a lot about SQLAlchemy, but I got my problem fixed.

Thanks to everyone.
