### ISSUE TITLE
Issue createing Sqlalchemy engine - "Can't load plugin: sqlalchemy.dialects:teradata"

### ISSUE THREAD

**Issue by jezlax** [Teradata/sqlalchemy-teradata#37]
I can read in data from TD fine, but need to setup a SQLAlchemy engine to leverage df.to_sql(), below is my setup and the error I'm receiving as well. Please advise. 

```import pandas as pd
import sqlalchemy

user = 'my.user'
pw = 'my_password'
host = '123.456.78.90'

td_engine = create_engine('teradata://'+ user +':' + pasw + '@'+ host + ':22/')
```

I'm getting the following error: NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:teradata 

In reading the SQLAlchemy Docs - it looks like Teradata isn't part of their core. I've also done ``!pip install sqlalchemy-teradata`` but I cannot import that package, throws a syntax error. 

Also for my host I'm just listing the IP of the server, is that correct? Thanks in advance.

**Comment by sandan** [comment]
If you need to import something from sqlalchemy-teradata, use `import sqlalchemy_teradata`. This is a convention for third party dialects. Yes, you can use the IP address for the host. You might want to look at the tutorials and examples in the [wiki](https://github.com/Teradata/sqlalchemy-teradata/wiki/Examples).

What version of sqlalchemy are you using?
