### ISSUE TITLE
Lock Row For Access When Using SQLAlchemy on Teradata

### ISSUE THREAD

**Issue by alexisrolland** [Teradata/sqlalchemy-teradata#39]
Hello,

We're using SQLAlchemy and Teradata-SQLAlchemy packages on top of our Teradata database. The problem we are facing is every SELECT executed by SQLAlchemy on top of Teradata would Lock the table, preventing other users to perform any operation on the table in parallel.

When not using SQLALchemy, we would usually build cover views as below and execute our SELECT statements on those views only (never on the tables directly).

```sql
REPLACE VIEW DATABASE.TABLE AS
LOCK ROW FOR ACCESS
SELECT * FROM DATABASE.TABLE;
```

This would allow several users to operate on top of the table without locking each others when doing simple selects.

Would you know a way to replicate that when the query / select is automatically generated by SQLAlchemy?

Thanks

**Comment by sandan** [comment]
Interesting. Just to clarify, you want to execute DDL whenever a select query happens then change the target of the query to the view and not the table. What if the query contains a join? Also, do you want this behavior when using the `select` (sqlalchemy.sql.expression.select) or `query`, or both? 

First thing this reminds me of is the decorator approach. SQLAlchemy has something like this with `@compiles`. Maybe you can make your own [custom expression](http://docs.sqlalchemy.org/en/latest/core/compiler.html#compiling-sub-elements-of-a-custom-expression-construct)? Or just [decorate the behavior of Select](http://docs.sqlalchemy.org/en/latest/core/compiler.html#changing-the-default-compilation-of-existing-constructs)?

```
from sqlalchemy.ext.compiler import compiles

@compiles(Select)
def select_from_cover(select, compiler, **kw):
  print('execute cover view logic')
  return compiler.visit_select(select, **kw)

 s = select([t1])
 print(s)
```

**Comment by alexisrolland** [comment]
Actually I don't want to perform any DDL. But from what I understand about Teradata, if you do a SELECT on a table without specifying LOCK ROW FOR ACCESS, it would lock the entire table preventing other users to run INSERT, UPDATE or DELETE statements in parallel.

This is why all SELECT operations should ideally be performed on the cover views including the LOCK ROW FOR ACCESS statement rather than tables.

**Comment by sandan** [comment]
Ok, perhaps I overcomplicated your question. You can use CreateView in base.py. Then just issue a select on the View. See https://bitbucket.org/zzzeek/sqlalchemy/wiki/UsageRecipes/Views.

**Comment by alexisrolland** [comment]
Hi @sandan 
So I'm thinking I should probably use the following `@compile` decorator and custom method but I'm not sure where / how to integrate that in my existing code?

```
from sqlalchemy.sql.expression import Select

@compiles(Select)
def prefix_select(select, compiler, **kw):
    return compiler.visit_select(select.prefix_with("LOCK ROW FOR ACCESS"), **kw)
```

At the moment I have a file *database.py* with the following:

```
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base, DeferredReflection
from sqlalchemy.orm import scoped_session, sessionmaker
from cryptography.fernet import Fernet
import configparser
import os


# Get configuration parameters
config = configparser.ConfigParser()
config.read(os.path.dirname(__file__) + '/global_parameter.ini')
host = config.get('DATABASE', 'host')
database = config.get('DATABASE', 'database')
user = config.get('DATABASE', 'user')
password = config.get('DATABASE', 'password').encode('utf-8')
cipher_key = config.get('DATABASE', 'cipher_key')

# Decrypt password
cipher = Fernet(cipher_key)
password = cipher.decrypt(password).decode('utf-8')

# Connect
engine = create_engine('teradata://' + user + ':' + password + '@' + host + ':22/' + database)
db_session = scoped_session(sessionmaker(autocommit=False, autoflush=False, bind=engine))

Base = declarative_base(cls=DeferredReflection)
Base.query = db_session.query_property()
```

And a file *model.py* which contains my tables classes. Example:

```
[...]
class MigrationPlanModel(Base):
    def migrationPlanDefaultId(context):
        return context.connection.execute(
            sql.select([func.coalesce(func.max(MigrationPlanModel.id), 0) + 1])
        ).scalar()

    __tablename__ = 'migration_plan'
    id = Column('migration_plan_id', Integer, primary_key=True, default=migrationPlanDefaultId)
    name = Column('migration_plan_name', String, nullable=False)
    status = Column('migration_plan_status', String, nullable=False)
    sourceEnvironment = Column('source_environment', String, nullable=False)
    targetEnvironment = Column('target_environment', String, nullable=False)
    team = Column('team', String, nullable=False)
    distributionList = Column('distribution_list', String, nullable=False)
    createdBy = Column('created_by', String, nullable=False)
    lastUpdatedBy = Column('last_updated_by', String, nullable=False)
    createdDate = Column('creation_date', DateTime, server_default=func.now())
    updatedDate = Column('last_update', DateTime, server_default=func.now(), onupdate=datetime.datetime.utcnow)
[...]
```

Would you have a clue by any chance?
Many thanks in advance for your help.

**Comment by alexisrolland** [comment]
I have tried the following:

```python
from sqlalchemy import create_engine
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.ext.declarative import declarative_base, DeferredReflection
from sqlalchemy.orm import scoped_session, sessionmaker
from cryptography.fernet import Fernet
import configparser
import os


# Get configuration parameters
config = configparser.ConfigParser()
config.read(os.path.dirname(__file__) + '/global_parameter.ini')
host = config.get('DATABASE', 'host')
database = config.get('DATABASE', 'database')
user = config.get('DATABASE', 'user')
password = config.get('DATABASE', 'password').encode('utf-8')
cipher_key = config.get('DATABASE', 'cipher_key')

# Decrypt password
cipher = Fernet(cipher_key)
password = cipher.decrypt(password).decode('utf-8')

# Connect
engine = create_engine('teradata://' + user + ':' + password + '@' + host + ':22/' + database)
db_session = scoped_session(sessionmaker(autocommit=False, autoflush=False, bind=engine))

# Adding prefix to every select to avoid table lock
@compiles(Select)
def prefix_select(select, compiler, **kw):
    return compiler.visit_select(select.prefix_with("LOCK ROW FOR ACCESS"), **kw)

Base = declarative_base(cls=DeferredReflection)
Base.query = db_session.query_property()
```

It worked in one way but it's actually adding the `LOCK ROW FOR ACCESS` after the `SELECT` instead of before :-/

> raise DatabaseError(i[2], u"[{}] {}".format(i[0], msg), i[0])
> sqlalchemy.exc.DatabaseError: (teradata.api.DatabaseError) (3706, "[42000] [Teradata][ODBC Teradata Driver][Teradata Database] Syntax error: expected something between the 'SELECT' keyword and the 'LOCK' keyword. ") [SQL: 'SELECT LOCK ROW FOR ACCESS columnname, columntype, columnlength, chartype, decimaltotaldigits, decimalfractionaldigits, columnformat, nullable, defaultvalue, idcoltype \nFROM dbc.ColumnsV \nWHERE DatabaseName=? AND TableName=?'] [parameters: ('dev_migration_tool', 'migration_object_teradata')]

It

**Comment by alexisrolland** [comment]
Issue solved with the solution described here:
https://stackoverflow.com/questions/49610780/avoid-deadlocks-using-teradata-and-sqlalchemy
