### ISSUE TITLE
How to specify TMODE=TERA when creating a session

### ISSUE THREAD

**Issue by alexisrolland** [Teradata/sqlalchemy-teradata#47]
Hello,
I haven't found anything related to session mode in the documentation. Is there a way to specify the session mode when creating a session?

Here is my current code as example:

```
# Connect
engine = create_engine('teradata://' + user + ':' + password + '@' + host + ':22/' + database)
db_session = scoped_session(sessionmaker(autocommit=False, autoflush=False, bind=engine))
db_session.execute('SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;')  # To avoid locking tables when doing select on tables
db_session.commit()
```

Thanks

**Comment by tserafim** [comment]
You should try the methods mentioned in [Custom DBAPI connect() arguments](http://docs.sqlalchemy.org/en/latest/core/engines.html#custom-dbapi-args)

**Comment by jayanthsai1998** [comment]
Hi alexisrolland,
            Have you found any solution regarding session mode, like how to set the session modes when establishing the connection?
