### ISSUE TITLE
SQLAlchemy Not Substituting Values into Query

### ISSUE THREAD

**Issue by karl-schelhammer-td** [Teradata/sqlalchemy-teradata#65]
I have a sqlalchemy query that uses some window functions to implement lag() over a column.  The backend is using Teradata if that matters.

I am receiving a database error from that suggests to me that the parameter values are not being correctly substituted.  If I run the bare query in the database, I get the exact same error.

The tables are defined as extensions to the base class and reflected from the database in the usual way.

The sqlalchemy code:

    name = 'some_column'
    query = self.session\
                .query(func.min(getattr(table,name))\
                    .over(partition_by=over_attrs,
                          order_by=getattr(table,name),
                          rows=(1,1)))

produces the following sql:

    SELECT min(my_table_1.my_date) 
    OVER (PARTITION BY my_table_1.ban, my_table_1.location 
    ORDER BY my_table_1.my_date ROWS 
    BETWEEN ? FOLLOWING AND ? FOLLOWING) AS anon_1 
    FROM schema.my_table AS my_table_1

The error message I get is:

    (teradata.api.DatabaseError) (3707, "[42000] [Teradata]
    [ODBC Teradata Driver][Teradata Database] Syntax error, 
    expected something like a name or a Unicode delimited identifier 
    or an integer between the 'BETWEEN' keyword and '?'. ") 
    [SQL: 'SELECT TOP 25 min(my_table_1.my_date) 
    OVER (PARTITION BY my_table_1.ban, my_table_1.location 
    ORDER BY my_table_1.my_date ROWS BETWEEN ? FOLLOWING AND ? FOLLOWING) AS anon_1 \n
    FROM schema.my_table AS my_table_1'] [parameters: (1, 1)] 
    (Background on this error at: http://sqlalche.me/e/4xp6)

If I run the query in database with the `?` replaced with (1,1), the query runs fine.  If I leave in the `?` then it fails with the exact same error as the sqlalchemy version.

Am I doing something wrong that would cause it to fail in this way or could this be a bug in sqlalchemy?

Versions:

    SQLAlchemy          1.2.8 
    sqlalchemy-teradata 0.1.0.dev0
    pyodbc              4.0.23 

I'm using the Teradata Database ODBC driver v 16.10.

**Comment by karl-schelhammer-td** [comment]
I confirmed that the query parameters are not being substituted by turning on echo=TRUE in create_engine().  Here is the log:

`2018-08-22 13:09:01,791 INFO sqlalchemy.engine.base.Engine SELECT TOP 25 min(schema. my_table_1. my_date) OVER (PARTITION BY schema. my_table_1.ban, schema. my_table_1.location ORDER BY schema. my_table_1. my_date ROWS BETWEEN ? FOLLOWING AND ? FOLLOWING) AS lag_dt `

**Comment by sandan** [comment]
When you compile the query, you should pass `.compile(compile_kwargs = {'literal_binds': True})`

**Comment by karl-schelhammer-td** [comment]
I will give that a try ASAP.
