### ISSUE TITLE
Produce non-beta PyPi Release

### ISSUE THREAD

**Issue by DepthDeluxe** [Teradata/sqlalchemy-teradata#70]
I have been trying to use this package in the past and am running into internal import requirements at my company.  We do not allow importing beta (development) packages into our internal repository.  It looks like the latest release is `0.1.0.dev0` on PyPi.  I'm not sure if this is affecting other people but I would certainly be using this package if not for these restrictions.

It would be great if you could more regularly release non-beta versions into PyPi.

**Comment by sandan** [comment]
@DepthDeluxe Thanks for the feedback! I'll be releasing one shortly today.

**Comment by sandan** [comment]
@DepthDeluxe -0.9.0dev0 is released. It is non-alpha, there are lots of enhancements relating to the type system and reflection. You can see the CHANGELOG.md in the dev/ branch, which is what the release is based of off.

**Comment by DepthDeluxe** [comment]
@sandan, this is still marked as `pre-release` by PyPI which is still causing me issues.  What's the harm in releasing a `0.0.1` release version?

![image](https://user-images.githubusercontent.com/4984331/45391298-43822980-b5d7-11e8-9b75-c41d70461bd4.png)
