### ISSUE TITLE
Incorrect complied SQL statement for not equals !=

### ISSUE THREAD

**Issue by karl-schelhammer-td** [Teradata/sqlalchemy-teradata#73]
I have found a bug with the sqlalchemy-teradata implimentation of the not equals operator.

I have defined a class that can be instantiated to produce a function that returns part of a filter clause.  Basically you pass it a table and it generates a SQL filter that I pass along to some other part of the workflow.

The class code is as follows:
```
class clocFilter():
    def __init__(self, attr_col):
        self.attr_col = attr_col
        
    def __call__(self, table):
        return self.do_filter(table)
        
    def do_filter(self, table):
        # set_trace()
        q_filter = or_(getattr(table, self.attr_col) != None,
                       getattr(table, self.attr_col) != 0,
                       getattr(table, self.attr_col) != 1)
        return q_filter
```

Make an instance of the class to filter on column named 'cloc':

`filter_cloc = clocFilter('cloc')`

Then I print the resulting SQL statement:

`print(filter_cloc(my_table))`

And the result is:
`schema.my_table.cloc IS NOT NULL OR schema.my_table.cloc != :cloc_1 OR schema.my_table.cloc != :cloc_2`

It should instead output:  
`schema.my_table.cloc IS NOT NULL OR schema.my_table.cloc <> :cloc_1 OR schema.my_table.cloc <> :cloc_2`

because in Teradata the not equals operator translates to `<>`.

Note that it does compile correctly for `getattr(table, self.attr_col) != None,`, but the comparison to the integer values fails.

**Comment by sandan** [comment]
Thanks @karl-schelhammer-td, I suggest using our dev branch for now. It has the fix.

**Comment by sandan** [comment]
I also suggest checking out teradatasqlalchemy, it uses a driver that doesn't need ODBC and has the updates in `dev`.
