### ISSUE TITLE
How to connect to Teradata with LDAP authentication

### ISSUE THREAD

**Issue by Jackie-You** [Teradata/sqlalchemy-teradata#75]
I have an issue when connecting to Teradata with sqlalchemy-teradata. My user_name,password and host is OK, but can't connect to Teradata successfully. I think it because of "LDAP authentication", i must use the "Authentication=LDAP" when i do the connection by MS ODBC. But how can i do it by sqlalchemy-teradata?

Below is the code, it's failed.
`from sqlalchemy import create_engine`
`import pandas as pd`
`path = r"C:\Users\xxx\Desktop\TEMP\201810\092620180600-xxx_confirm_7428.csv"`
`df = pd.read_csv(path)`
`engine = create_engine('teradata://XXX:XXX@xxx.xxx.com:XXX')`
`pd.io.sql.to_sql(df,'test_pick',engine,if_exists='append')`

![error1](https://user-images.githubusercontent.com/32482902/46391883-a9169100-c711-11e8-89da-f5d826856b70.PNG)

Failed use ODBC

Successful use ODBC

**Comment by sandan** [comment]
See https://github.com/Teradata/sqlalchemy-teradata/issues/1
