### ISSUE TITLE
Submitting issues for teradatasqlalchemy

### ISSUE THREAD

**Issue by Sledge-** [Teradata/sqlalchemy-teradata#81]
Now that 16.20 is using the teradatasqlalchemy package instead of this one, where should we go to submit new issues?

https://pypi.org/project/teradatasqlalchemy/

The homepage here links to a connectivity issues forum, which only covers a small subset of potential issues.  https://community.teradata.com/t5/Connectivity/bd-p/DevXConnectivityBoard

**Comment by tomcnolan** [comment]
Hi, I'm the technical lead for the `teradatasql` package and the `teradatasqlalchemy` package. Both packages are fully-supported products.

If you are a Teradata customer, you can open an incident with Teradata customer support, please visit Teradata Access at https://access.teradata.com/

Otherwise, you can report a problem in our public Connectivity Forum at http://community.teradata.com/t5/Connectivity/bd-p/DevXConnectivityBoard

Please note that the "Connectivity" title refers to connectivity *products* rather than problems.

**Comment by KrishanBhasin** [comment]
Hi @tomcnolan, that link now goes directly to the generic [Teradata Community Home](https://community.teradata.com/community).
Could you please advise where else to report issues?

I am currently attempting to use `teradatasqlalchemy` to connect to my Teradata instance, but the SQL it generates does not appear to conform to the Teradata dialect requirements:
```
 sqlalchemy.exc.OperationalError: (teradatasql.OperationalError) [Version 16.20.0.50] [Session 17260840] [Teradata Database] [Error 3707] Syntax error, expected something like a name or a Unicode delimited identifier or an 'UDFCALLNAME' keyword between ')' and ';'.
E                at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1083
E                at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1099
E                at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1164
E                at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1332
E                at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:468
E                at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:340
E                at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
E                at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2021
E                at database/sql.ctxDriverQuery ctxutil.go:48
E                at database/sql.(*DB).queryDC.func1 sql.go:1464
E                at database/sql.withLock sql.go:3032
E                at database/sql.(*DB).queryDC sql.go:1459
E                at database/sql.(*Conn).QueryContext sql.go:1701
E                at main.goCreateRows goside.go:597
E                at main._cgoexpwrap_e6e101e164fa_goCreateRows _cgo_gotypes.go:331
E                at runtime.call64 asm_amd64.s:574
E                at runtime.cgocallbackg1 cgocall.go:316
E                at runtime.cgocallbackg cgocall.go:194
E                at runtime.cgocallback_gofunc asm_amd64.s:826
E                at runtime.goexit asm_amd64.s:2361
E               [SQL: SELECT TOP 5 "TEST_VAR", "YEAR_MONTH" 
E               FROM (SELECT "MY_TABLE"."TEST_VAR" AS "TEST_VAR", "MY_TABLE"."YEAR_MONTH" AS "YEAR_MONTH" 
E               FROM "MY_TABLE" 
E               WHERE "MY_TABLE"."ACCT_ID" = 47)]
E               (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by tomcnolan** [comment]
> that link now goes directly to the generic Teradata Community Home.
> Could you please advise where else to report issues?

@KrishanBhasin For community support, please visit the [Teradata Community forums](https://community.teradata.com/). Either the "Teradata Database" forum or the "Teradata Tools and Utilities" forum would be appropriate for this issue.

**Comment by sandan** [comment]
@KrishanBhasin Could you also post the teradatasqlalchemy code you used that generated the error? Perhaps you are missing a call to [alias](https://docs.sqlalchemy.org/en/13/core/selectable.html#sqlalchemy.sql.expression.alias)?

**Comment by KrishanBhasin** [comment]
@sandan looks like you're spot on! I've moved on to a new error to solve, thank you for getting back to me on this!
