### ISSUE TITLE
Compatibility with SQLAlchemy 2.0.0

### ISSUE THREAD

**Issue by jasheldo** [Teradata/sqlalchemy-teradata#94]
SQLAlchemy 2.0.0 has been officially released and the current version of `teradatasqlalchemy` is incompatible. Is there an update in the pipeline?

**Comment by uyjeff18** [comment]
Hi jasheldo. Teradata is currently testing a new version of teradataml and teradatasqlalchemy that is compatible with sqlalchemy 2.0. This is targeted for release in late April 2023. Meanwhile, please stay on sqlalchemy 1.4.

**Comment by jasheldo** [comment]
Thank you!
